require ('pry-byebug')
require_relative ('../models/instrument')
require_relative( '../models/stock' )
require_relative( '../models/till' )


Instrument.delete_all()
Stock.delete_all()


guitar1 = Instrument.new({'brand' => "Fender 52 Reissue", 'type' => "Guitar", 'cost' => 1499, 'quantity' => 10})
guitar1.save()
guitar2 = Instrument.new({'brand' => "Fender Stratocaster", 'type' => "Guitar", 'cost' => 499, 'quantity' => 10})
guitar2.save()
guitar3 = Instrument.new({'brand' => "Gibson ES-335", 'type' => "Guitar", 'cost' => 2999, 'quantity' => 5})
guitar3.save()
guitar4 = Instrument.new({'brand' => "Epiphone Dot 335", 'type' => "Guitar", 'cost' => 349, 'quantity' => 15})
guitar4.save()
guitar5 = Instrument.new({'brand' => "Gretsch G2420 Streamliner", 'type' => "Guitar", 'cost' => 364, 'quantity' => 15})
guitar5.save()
guitar6 = Instrument.new({'brand' => "Fender Jag-Stang ", 'type' => "Guitar", 'cost' => 549, 'quantity' => 10})
guitar6.save()
guitar7 = Instrument.new({'brand' => "Rick Nielsen’s Five-Neck Hamer", 'type' => "Guitar", 'cost' => 5000, 'quantity' => 3})
guitar7.save()
guitar8 = Instrument.new({'brand' => "Fender Duo Sonic", 'type' => "Guitar", 'cost' => 488, 'quantity' => 15})
guitar8.save()
guitar9 = Instrument.new({'brand' => "Yamaha F310", 'type' => "Guitar", 'cost' => 149, 'quantity' => 20})
guitar9.save()
guitar10 = Instrument.new({'brand' => "Alhambra Crossover CS-3 CW E5", 'type' => "Guitar", 'cost' => 999, 'quantity' => 10})
guitar10.save()
bass1 = Instrument.new({'brand' => "Fender Deluxe Active P Special", 'type' => "Bass", 'cost' => 785, 'quantity' => 10})
bass1.save()
bass2 = Instrument.new({'brand' => "Sterling by Music Man", 'type' => "Bass", 'cost' => 799, 'quantity' => 10})
bass2.save()
bass3 = Instrument.new({'brand' => "Yamaha BB Series BB424", 'type' => "Bass", 'cost' => 399, 'quantity' => 15})
bass3.save()
bass4 = Instrument.new({'brand' => "Epiphone Goth Thunderbird VI", 'type' => "Bass", 'cost' => 299, 'quantity' => 15})
bass4.save()
bass5 = Instrument.new({'brand' => "Ibanez GSR200", 'type' => "Bass", 'cost' => 199, 'quantity' => 20})
bass5.save()
kit1 = Instrument.new({'brand' => "Ludwig Club Date ", 'type' => "Drums", 'cost' => 925, 'quantity' => 5})
kit1.save()
kit2 = Instrument.new({'brand' => "Gretsch Catalina", 'type' => "Drums", 'cost' => 800, 'quantity' => 6})
kit2.save()
kit3 = Instrument.new({'brand' => "Pearl Export Series", 'type' => "Drums", 'cost' => 785, 'quantity' => 7})
kit3.save()

# stock1 = Stock.new({'instrument_id' => guitar1.id})
# stock1.save()
# stock2 = Stock.new({'instrument_id' => guitar3.id})
# stock2.save()
# stock3 = Stock.new({'instrument_id' => kit1.id})
# stock3.save()
# stock4 = Stock.new({'instrument_id' => bass1.id})
# stock4.save()
# stock5 = Stock.new({'instrument_id' => guitar7.id})
# stock5.save()

binding.pry
nil
